In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# cv2 computer vision library for loading images
import cv2
# tensorflow for Convolutional Neural Network (CNN)
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, Activation, Conv2D, MaxPooling2D

In [5]:
import os

In [6]:
# files imported from Kaggle dataset: Rock, Paper, Scissors
# https://www.kaggle.com/drgfreeman/rockpaperscissors/data
print(os.listdir("./"))

['paper', 'RPS1.ipynb', 'RPS3.ipynb', 'rps-cv-images', 'Import Images and Transform.ipynb', '.ipynb_checkpoints', 'scissors', 'test', 'rock', 'README_rpc-cv-images.txt', 'RPS2.ipynb']


In [7]:
rock_dir = "./rock"
paper_dir = "./paper"
scissors_dir ="./scissors"

In [8]:
rock_cat = 0
paper_cat = 1
scissors_cat = 2

In [19]:
def create_bw_img_array(filename):
    img_array = cv2.imread(filename,cv2.IMREAD_GRAYSCALE)
    new_img_array = cv2.resize(img_array, dsize=(100, 100))
    return new_img_array

In [30]:
def create_col_img_array(filename):
    img_array = cv2.imread(filename,cv2.IMREAD_COLOR)
    new_img_array = cv2.resize(img_array, dsize=(100, 100))
    return new_img_array

In [39]:
f = './rock/eJ5fbY23rZWUULxO.png'
bw_image = create_bw_img_array(f)
bw_image

array([[65, 66, 70, ..., 53, 50, 49],
       [66, 69, 71, ..., 50, 48, 47],
       [69, 70, 73, ..., 49, 48, 47],
       ...,
       [80, 80, 81, ..., 63, 64, 62],
       [80, 79, 79, ..., 62, 63, 60],
       [79, 78, 79, ..., 62, 62, 59]], dtype=uint8)

In [70]:
for x in range(100):
    print(np.max(bw_image[:,x]))

103
104
104
105
106
106
106
106
107
107
108
108
108
108
109
110
108
109
109
109
109
109
109
111
110
110
111
112
112
112
111
109
109
108
106
104
103
144
175
186
191
201
203
201
203
195
186
179
172
175
187
209
220
224
233
235
228
213
199
198
196
190
186
183
185
185
186
188
189
190
184
180
181
176
171
173
170
169
172
175
178
174
176
181
180
183
183
181
180
182
180
178
176
175
175
176
176
174
174
175


In [43]:
bw_image[:,1]

array([ 66,  69,  70,  71,  72,  73,  75,  76,  77,  78,  79,  79,  81,
        82,  83,  85,  86,  87,  87,  88,  88,  90,  90,  92,  93,  93,
        93,  94,  95,  95,  97,  98,  97,  98,  98,  99, 102, 104, 103,
       104, 103, 103, 103, 103, 103, 104, 102, 103, 103, 103, 102, 102,
       103, 101, 101, 102, 101, 101, 102, 102, 102, 101, 100,  99,  98,
        97,  96,  97,  98,  98,  97,  97,  96,  96,  96,  95,  94,  93,
        92,  92,  92,  91,  89,  89,  89,  88,  87,  86,  86,  86,  86,
        85,  84,  82,  83,  82,  81,  80,  79,  78], dtype=uint8)

In [40]:
f = './rock/eJ5fbY23rZWUULxO.png'
col_image = create_col_img_array(f)
col_image

array([[[ 21, 100,  15],
        [ 22, 102,  15],
        [ 26, 106,  18],
        ...,
        [  1,  84,  12],
        [  0,  82,   9],
        [  0,  80,   9]],

       [[ 22, 101,  16],
        [ 24, 105,  18],
        [ 25, 107,  19],
        ...,
        [  0,  81,  11],
        [  0,  78,   8],
        [  0,  76,   8]],

       [[ 23, 104,  18],
        [ 24, 106,  18],
        [ 27, 109,  21],
        ...,
        [  0,  80,  10],
        [  0,  78,   8],
        [  0,  77,   9]],

       ...,

       [[ 30, 119,  24],
        [ 29, 119,  24],
        [ 29, 121,  24],
        ...,
        [ 19,  97,  15],
        [ 20,  98,  17],
        [ 17,  95,  14]],

       [[ 30, 118,  25],
        [ 28, 118,  22],
        [ 27, 119,  22],
        ...,
        [ 18,  96,  15],
        [ 19,  96,  16],
        [ 16,  93,  13]],

       [[ 29, 117,  23],
        [ 27, 118,  21],
        [ 28, 119,  22],
        ...,
        [ 18,  95,  15],
        [ 18,  95,  14],
        [ 15,  92,  12]]

In [66]:
col_image.shape

(100, 100, 3)

In [38]:
dims = bw_image.shape
dims

(100, 100)

In [61]:
bw_image[5].sum()

8267

In [60]:
np.average(bw_image[5])

82.67

In [71]:
def image_row(arr, r, loop = dims[1]):
    for c in range(loop):
        print(arr[r,c])

In [72]:
def image_column(arr, c, loop = dims[0]):
    for r in range(loop):
        print(arr[r,c])

In [73]:
print(np.average(bw_image[:,0]))

90.43


In [74]:
print(np.average(bw_image[0,:]))

80.61


In [82]:
# print average for each row
bw_row_avgs = []
for i in range(dims[0]):
    bw_row_avgs.append(np.average(bw_image[i,:]))
print(np.average(bw_row_avgs))
print(np.max(bw_row_avgs))

106.89049999999997
142.77


In [84]:
bw_col_avgs = []
for i in range(dims[1]):
    bw_col_avgs.append(np.average(bw_image[:,i]))
print(np.average(bw_col_avgs))
print(np.max(bw_col_avgs))

106.89050000000002
141.06
